### ISSUE TITLE
'pun_pre_hook_root_cmd' is undefined

### ISSUE THREAD

**Issue by nlvw** [OSC/ood-ansible#110]
https://github.com/OSC/ood-ansible/blob/b6d99d6358e95db7942a032d15c01b7c41036a86/templates/ood_portal.yml.j2#L316

https://github.com/OSC/ood-ansible/blob/b6d99d6358e95db7942a032d15c01b7c41036a86/defaults/main/ood_portal.yml#L63

Moving from 1.8.1 to the new version of this role (2.0.0) I ran into the following error due to an undefined variable.  I had to manually set this to null to bypass the error.

![image](https://user-images.githubusercontent.com/5723368/121067055-d2700080-c787-11eb-94bd-f4a70d35bcef.png)

I have node/rnode enabled in-order to allow interactive apps to work.  Do I need to set these pun hooks to something other then null?

**Comment by johrstrom** [comment]
No that's a bug from copying + pasting. Thanks for the ticket!  I'll try to get it fixed today. pre hooks are unrelated to interactive apps.
