### ISSUE TITLE
deprecate ood-portal.conf.j2 template

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-ansible#128]
We need to deprecate the use of `ood_portal.conf.j2`.  I added it initially as a way for folks to write new directives but it's just too much to maintain. Folks should get by with just adding new conf files to conf.d.

I don't know how to get ansible to signify that this is deprecated, but we should use that mechanism if it exists.

**Comment by sjpb** [comment]
I seem to remember I've used this before for deprecated stuff - it's nastily noisy so should get some attention, but shouldn't actually break things:

https://stackoverflow.com/a/63557091/916373

**Comment by sandermitre** [comment]
Am I missing something or is the task logic only in place to use the templates? I see the note about using the defaults with the --extra-vars=@overrides.yml, but won't running the configure option always copy the template?

**Comment by johrstrom** [comment]
Templates in general, yes, but `ood_portal.conf.j2` specifically we need to get rid of.  `update_ood_portal`(what ships with OOD) has good support for Debian now.  So we can directly use OOD's templating through `update_ood_portal` to generate an `ood_portal.conf` instead of this library templating that j2 file.

This is the config that drives this behavior and this is the default. Setting it to false, and using this library's `ood_portal.conf.j2` is being deprecated.
```
ood_portal_generator: true
```

Hope that makes sense!

**Comment by sandermitre** [comment]
That makes sense.

Not to get too far into the weeds on this, but were do the files in default factor into the setup? I need to augment either the role or playbook to add in items which aren't covered in the role. One of the changes is I was just going to copy over the ood_portal.yml as opposed to using the template. Does the role have an option to do this?

As always thanks for your work on this project!

**Comment by johrstrom** [comment]
> One of the changes is I was just going to copy over the ood_portal.yml as opposed to using the template.

Got it. So the defaults in `defaults/main/ood_portal.yml` are going to be used to template the `ood_portal.yml.j2` which in turn is placed to `/etc/ood/config/ood_portal.yml`. We'll do that templating forever. OOD then takes that config to generate the httpd portal config (through `update_ood_portal`).

If you want default values - just don't supply any `--extra-vars`. We use the same defaults OOD does and/or have blocks like this that will actually template a commented default config (as it appears in the original). 

https://github.com/OSC/ood-ansible/blob/a068982def857662c6c5590933a62c2e3d5cc288/templates/ood_portal.yml.j2#L11-L13

**Comment by sandermitre** [comment]
Got it! This makes a lot more sense to me now, and I was able to mimic our existing configuration so perfect.

I still need to add installing mellon (which is our auth method) and the various certificates around that and ssl. I think I can do this using the playbook which will invoke the role later on using includ_role https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html unless there is an existing method to add those changes as well.

**Comment by sandermitre** [comment]
Got it thanks. I appreciate your tolerance on the thread drift on this issue. If I end up finding any way to easily extend the role to include this I will see if I can push it back, but I'm probably just going to lump into an extended playbook at this point.

**Comment by johrstrom** [comment]
NP at all.

**Comment by johrstrom** [comment]
using `ood_portal_generator: false` is deprecated now in 3.0 and will be pulled in some future version. Folks should refer to the changelog to see when this occurs.
