### ISSUE TITLE
Package clash

### ISSUE THREAD

**Issue by sjpb** [OSC/ood-ansible#175]
I've got a Rocky Linux 8.6 machine with the `ondemand` package installed. Trying to run this role on it with `ondemand_package == "latest"` I got a depsolve failure (same as shown below). I assume this is due to some package clash with an older version:?

```
[root@caas15-login-0 rocky]# dnf list ondemand
Installed Packages
ondemand.x86_64                                       2.0.28-1.el8                                        @ondemand-web
Available Packages
ondemand.x86_64                                       2.0.29-1.el8                                        ondemand-web
```

However trying to remove the old package (and dependencies) still doesn't work:
```
[root@caas15-login-0 rocky]# dnf remove -y ondemand
<snip>
[root@caas15-login-0 rocky]# dnf install ondemand-2.0.29
Last metadata expiration check: 0:01:51 ago on Wed 16 Nov 2022 10:24:22 AM UTC.
Error: 
 Problem: package ondemand-2.0.29-1.el8.x86_64 requires ondemand-nodejs = 2.0-3.el8, but none of the providers can be installed
  - package ondemand-nodejs-2.0-3.el8.x86_64 requires nodejs >= 1:14.0, but none of the providers can be installed
  - conflicting requests
  - package nodejs-1:14.20.1-2.module+el8.7.0+1071+4bdda2a8.x86_64 is filtered out by modular filtering
  - package nodejs-1:16.17.1-1.module+el8.6.0+1046+80feca58.x86_64 is filtered out by modular filtering
  - package nodejs-1:18.9.1-1.module+el8.7.0+1072+5b168780.x86_64 is filtered out by modular filtering
  - package nodejs-1:16.14.0-2.module_el8+13804+34326f90.x86_64 is filtered out by modular filtering
```

so I'm not quite sure what's going on here?

**Comment by johrstrom** [comment]
The role should have take care of upgrades. Node 12 is end of life so we had to upgrade to node 14. You should be able to `dnf module enable nodejs:14` and then it'll be sorted.

**Comment by sjpb** [comment]
I was using an old version of the role, which doesn't work with the default `ondemand_package: latest`. Clearly that's not right, but it's also likely to happen given the default. But tying role versions to e.g. rpm versions seems hard.

Feel free to close.

**Comment by johrstrom** [comment]
Yea sorry about that, I updated the role for the same. It's an odd spot to have updated our dependencies like that, but Node going EOL kinda forced our hand. A thousand apologies for the difficulties.  Let me know if the role needs further updating.

**Comment by sjpb** [comment]
Reading again my comment "not right" sounds snarky - I meant "not the right way for me to be using the role" :-). Apologies for the noise!

**Comment by johrstrom** [comment]
No problem at all! (yea text is a bit hard to read subtext!)
