### ISSUE TITLE
ansible-galaxy error due to dependency on a collection

### ISSUE THREAD

**Issue by bedroge** [OSC/ood-ansible#199]
We got the following error when trying to install this role:
```
$ ansible-galaxy install osc.open_ondemand
Starting galaxy role install process
- downloading role 'open_ondemand', owned by osc
- downloading role from https://github.com/OSC/ood-ansible/archive/v3.0.2.tar.gz
- extracting osc.open_ondemand to /home/bob/.ansible/roles/osc.open_ondemand
- osc.open_ondemand (v3.0.2) was installed successfully
ERROR! Expected role dependencies to be a list. Role osc.open_ondemand (v3.0.2) has meta/requirements.yml {'collections': ['community.general']}
```

Apparently, this is because it's not possible for a role to depend on a collection, see for instance https://github.com/ansible/ansible/issues/77907#issuecomment-1137254399, https://github.com/ansible/ansible/issues/62847, and https://github.com/ansible/ansible/issues/76030#issuecomment-942520399.

**Comment by johrstrom** [comment]
Thanks for the issue.  I'm removing the dependencies because they're used in the now deprecated building from source anyhow. So (a) not many folks need it anyhow and (b) we're going to remove all of that functionality at some point anyhow.

**Comment by bedroge** [comment]
Thanks for the quick fix!
