### ISSUE TITLE
Consider ASDF to install specific lang interpreter versions

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood-ansible#2]
I am not sure how well ASDF works when attempting to install things to the system instead of just as a user, but it and its plugins provide a huge number of versions of Ruby and Node. 

https://github.com/asdf-vm/asdf

**Comment by johrstrom** [comment]
Sure, anyone seeing this in the interim can look at this role.  Maybe we set a toggle to install the system ruby/nodejs, then folks can compose a playbook with this other role?  

https://github.com/cimon-io/ansible-role-asdf

**Comment by MorganRodgers** [comment]
My Ansible-foo is non-existent. Sounds like it could work.

**Comment by ericfranz** [comment]
I thought asdf was more of a developer utility. Is it actually used by sys admins to manage system wide installs of Ruby, Python, etc?

@treydock?

**Comment by treydock** [comment]
Personally, I would not use outside of development. For system level things I rely on OS packages whenever possible. I have used RVM and virtualenv before for system level things but prefer not to if possible. If it's isolated from interfering with OS packages and can be automated then think is fine.

**Comment by ericfranz** [comment]
Based on Treys response I’ll close this issue as not doing.
