### ISSUE TITLE
ood_auth_openidc does not support multi-valued options

### ISSUE THREAD

**Issue by ltalirz** [OSC/ood-ansible#211]
Some OIDC apache options are multi-valued, like
https://github.com/OSC/ood-ansible/blob/beb85713cf3b0e55c775e4f4bf976284900ed6e6/molecule/default/vars/oidc_portal.yml#L27

It seems to me it is currently not possible to set such options via the ood_auth_openidc variable

```
OIDCStateMaxNumberOfCookies: "10 true" 
```
results in `OIDCStateMaxNumberOfCookies '10 true'` in the apache config file, which will fail.

```
OIDCStateMaxNumberOfCookies: [10, true] 
```
results in a quoted list, also not correct.

The issue is that this approach
https://github.com/OSC/ood-ansible/blob/beb85713cf3b0e55c775e4f4bf976284900ed6e6/templates/auth_openidc.conf.j2#L3

is not general enough here.

One could do the following (tested)
```yaml
{{ key }} {% if value is iterable and (value is not string and value is not mappi
ng) %}{{ value | map('quote') | join(' ') }}{% else %}{{ value | quote }}{% endif 
%}
```

Now, the following will produce the correct result
```
OIDCStateMaxNumberOfCookies: [10, true] 
```

An alternative would be to create a custom filter module

**Comment by johrstrom** [comment]
> Some OIDC apache options are multi-valued, like

> https://github.com/OSC/ood-ansible/blob/beb85713cf3b0e55c775e4f4bf976284900ed6e6/molecule/default/vars/oidc_portal.yml#L27

So I think what you want to do here is use this config `oidc_state_max_number_of_cookies` instead of supplying it in the key value map `ood_auth_openidc`

https://github.com/OSC/ood-ansible/blob/beb85713cf3b0e55c775e4f4bf976284900ed6e6/templates/ood_portal.yml.j2#L457-L463

I think `ood_auth_openidc` is for things that aren't directly supported in `ood_portal.yml`, which `oidc_state_max_number_of_cookies` is.

However, using `oidc_state_max_number_of_cookies` does template out the conf file like so (no quotes).

```conf
OIDCStateMaxNumberOfCookies 3 true
```

**Comment by johrstrom** [comment]
That said - I'm looking into your fix for `ood_auth_openidc` for other configs that may be like this.

**Comment by johrstrom** [comment]
Would #212 work for you?

**Comment by johrstrom** [comment]
I think you need to configure it as `iterable` in the config. Can you try this? I'll reopen this ticket for docs and a test case.

```yaml
ood_auth_openidc:
  OIDCStateMaxNumberOfCookies:
    - 10
    - true
  OtherStringValue: 'yesplz'
```

**Comment by xpillons** [comment]
Thanks @johrstrom I confirm it need an iterable. You can also specify it in this format too
```yml
ood_auth_openidc:
  OIDCStateMaxNumberOfCookies: [10 true]
 ```

**Comment by ltalirz** [comment]
Yes, as described at the end of the issue
