### ISSUE TITLE
Cleanest way to enable auto_queues (or similar attributes) with ood-ansible

### ISSUE THREAD

**Issue by Trigil** [OSC/ood-ansible#245]
Hello!

I'm currently looking into how to enable bc_desktop auto_queues attribute from the ansible role. I guess auto_accounts and auto_qos work the same way.

If I am not mistaken, this should allow the user to select a slurm partition (or account or qos) directly from a list, limited to what they have access to, when they want to run a remote desktop?

If so, can these options be activated directly in the cluster.yml, in the bc_desktop part?

Thanks for your help!

Tristan

**Comment by johrstrom** [comment]
You don't have to do anything to enable them, just use them in the `form.yml` files like the one below. 

https://github.com/OSC/ood-ansible?tab=readme-ov-file#ood_apps-example

That said - you should also enable `bc_dynamic_js` so the lists that are populated are dynamic (i.e., hide & show the appropriate fields).

https://github.com/OSC/ood-ansible/blob/39e64b9966924d4795fc1c171c41ff509aa7927f/templates/ondemand.yml.j2#L32

**Comment by Trigil** [comment]
It works! I was using them in the wrong part of the cluster.yml (in attributes and not in form), thank you! :)

**Comment by johrstrom** [comment]
OK great! then I'll close this ticket as you seemed to have got it sorted. Just open more tickets if you need.
