### ISSUE TITLE
How to patch an app git repo?

### ISSUE THREAD

**Issue by Trigil** [OSC/ood-ansible#246]
Hello!

I'm wondering what's the best way to apply a patch to an app's git repo clone.

To be more precise, here is what I have in defaults/main/apps.yml
ood_install_apps:
    codeserver:
      repo: https://github.com/OSC/bc_osc_codeserver.git
      dest: "{{ ood_sys_app_dir }}"
      version: master
      umask: '022'

And I have a bc_osc_codeserver.patch file in files/

Is there a way to give the path to the patch file directly in the apps.yml? Or is there no other way than to somehow apply it in tasks/main.yml (even if it's not where the git repo is given)?

Thanks in advance for your help, have a nice day!

Tristan

**Comment by johrstrom** [comment]
Fork that repository and then you can do whatever you want with it. Once you have the fork - you can occasionally sync with our app, but you'll have the app all to yourself to modify.

**Comment by Trigil** [comment]
Ok, thank you for your quick answer! I'll do that :)
