### ISSUE TITLE
Launch this role on Ansible Galaxy

### ISSUE THREAD

**Issue by guimaluf** [OSC/ood-ansible#37]

**Comment by guimaluf** [comment]
I think now we just need this: https://galaxy.ansible.com/docs/contributing/importing.html

**Comment by johrstrom** [comment]
This got closed a little bit early, but we have enabled this on Galaxy now.  The automation isn't working quite yet, but I was able to manually import the role into the organization. 

You can now get this role off of galaxy through `osc.open_ondemand`.
