### ISSUE TITLE
Files app doesn't boot

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-ansible#6]
The files application doesn't boot correctly, giving this error. It's unclear why exactly but likely due to a PATH problem because that file does end up existing here `/opt/ood/passenger-6.0.4/src/nodejs_supportlib/phusion_passenger/line_reader.js`.

```bash
App 969 output: internal/modules/cjs/loader.js:583
App 969 output:     throw err;
App 969 output:     ^
App 969 output: 
App 969 output: Error: Cannot find module 'phusion_passenger/line_reader'
App 969 output:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
App 969 output:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
App 969 output:     at Module.require (internal/modules/cjs/loader.js:637:17)
App 969 output:     at Module.require (/opt/ood/passenger-6.0.4/src/helper-scripts/node-loader.js:80:25)
App 969 output:     at require (internal/modules/cjs/helpers.js:22:18)
App 969 output:     at Object.<anonymous> (/opt/ood/passenger-6.0.4/src/helper-scripts/node-loader.js:121:18)
App 969 output:     at Module._compile (internal/modules/cjs/loader.js:689:30)
App 969 output:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
App 969 output:     at Module.load (internal/modules/cjs/loader.js:599:32)
App 969 output:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[ E 2019-10-31 15:02:48.1906 878/To age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/ood/apps/sys/files: The application process exited prematurely.
```

**Comment by johrstrom** [comment]
Adding this line to the `pun.conf.erb` fixes this, but I don't want to modify that file directly. Maybe add it to the `/etc/ood/profile`?  It's unclear how this works in the RPM install.

`passenger_env_var NODE_PATH /opt/ood/passenger/src/nodejs_supportlib;`

**Comment by treydock** [comment]
That's not necessary with RPM install of OnDemand.  I am running ondemand master branch built into RPMs and files app boots just fine.

**Comment by treydock** [comment]
For the RPM install the path is here: `/opt/ood/ondemand/root/usr/share/passenger/node/phusion_passenger/line_reader.js`

The file `/opt/ood/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/locations.ini` used by the PUN nginx config sets the path:

```
[root@ood ~]# grep node /opt/ood/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/locations.ini
node_libdir=/opt/rh/ondemand/root/usr/share/passenger/node
```

This is a by-product of doing the entire build of passenger inside `scl enable ondemand` block that "just works". Updating `locations.ini` is probably the best thing to do if your not installing things to the same place that `ondemand-passenger` expects. The file `locations.ini` is going to get overwritten with each update of `ondemand-passenger`.

**Comment by treydock** [comment]
I have trouble reading Ansible but looks like your downloading tar ball and copying files, that will not produce a useful `locations.ini` but maybe you can build one based on where you put things.  This is full `locations.ini` from `ondemand-passenger` RPM:

```
[locations]
packaging_method=rpm
bin_dir=/opt/rh/ondemand/root/usr/bin
support_binaries_dir=/opt/rh/ondemand/root/usr/lib64/passenger/support-binaries
lib_dir=/opt/rh/ondemand/root/usr/lib64/passenger
helper_scripts_dir=/opt/rh/ondemand/root/usr/share/passenger/helper-scripts
resources_dir=/opt/rh/ondemand/root/usr/share/passenger
include_dir=/opt/rh/ondemand/root/usr/share/passenger/include
doc_dir=/opt/rh/ondemand/root/usr/share/doc/passenger
ruby_libdir=/opt/rh/ondemand/root/usr/share/ruby/vendor_ruby
node_libdir=/opt/rh/ondemand/root/usr/share/passenger/node
apache2_module_path=/opt/rh/ondemand/root/usr/lib64/httpd/modules/mod_passenger.so
ruby_extension_source_dir=/opt/rh/ondemand/root/usr/share/passenger/ruby_extension_source
nginx_module_source_dir=/opt/rh/ondemand/root/usr/share/passenger/ngx_http_passenger_module
```

**Comment by johrstrom** [comment]
Awesome, thanks @treydock that was exactly it. It was previously set to something weird that didn't work (obviously).  I must have just guessed and filled something in.
