### ISSUE TITLE
Nodejs version is not necessarily correct

### ISSUE THREAD

**Issue by SpontaneousDuck** [OSC/ood-ansible#61]
ood now requires nodejs v10 for atleast the shell app. When on Ubuntu 18.04, this is not available through apt. Should I make a PR to install from somewhere else so we can get the correct version?

**Comment by johrstrom** [comment]
Hey, sorry about that! We don't have a lot of Ubuntu users. 

It looks like if we do this `curl -sL https://deb.nodesource.com/setup_10.x | bash -` it'll setup the right repository for the `nodejs` package install. 

Looks like a good spot may be here, in between these tasks.
https://github.com/OSC/ood-ansible/blob/5cb8db91cd74039712a6e83a542952aec107f0a9/tasks/deps.yml#L9-L14

If you want to submit the PR that'd be just fine! It'll take me a minute to spawn a container and test it out.

**Comment by msquee** [comment]
For posterity, this issue originated here https://github.com/OSC/ondemand/pull/545

**Comment by johrstrom** [comment]
Fixed in #62 (at least for Debians).
