### ISSUE TITLE
OOD-ansible has old repos? What about other packages?

### ISSUE THREAD

**Issue by datakid** [OSC/ood-ansible#64]
I was just reading through the ansible playbook - I noticed that it still references the [ood 1.7.1 repos](https://github.com/OSC/ood-ansible/blob/b00441abd3c6c263de448fc3286a6bcf651adf60/defaults/main.yml#L117).

Does that mean [the other software references](https://github.com/OSC/ood-ansible/blob/b00441abd3c6c263de448fc3286a6bcf651adf60/defaults/main.yml#L79) are a little out of date?

**Comment by johrstrom** [comment]
I'm working on updating it, I just got held up in support for centos:8 and other stuff.

But no, the dependencies like nginx and passenger didn't update from 1.7 to 1.8.
