### ISSUE TITLE
Fails to run on RHEL 7 due to missing var file RedHat-scl.yml

### ISSUE THREAD

**Issue by mrobbert** [OSC/ood-ansible#65]
I'm trying to install OOD on a RHEL 7 host using this ansible role and found that it fails to run due to an include in task/main.yml (  include_vars: "{{ ansible_distribution }}-scl.yml" ) which doesn't exist for RedHat. 
I was able to get it to run by copying the vars/CentOS-scl.yml to vars/RedHat-scl.yml and then remove the following lines from that file:

additional_rpm_installs:
- centos-release-scl

I can submit a pull request if you'd like, but maybe there is a cleaner way to fix that problem.

**Comment by johrstrom** [comment]
Thanks for the ticket! Yea I think a PR would be great if you have something that works for you, or as you indicate the fix if fairly easy so I could as well.  But yea for now, everything OS distribution specific is in "vars/{{ ansible_distribution }}-scl.yml" so the fix you've identified is appropriate.

**Comment by mrobbert** [comment]
Here is my pull request to fix this issue: #66

**Comment by johrstrom** [comment]
Fixed in #66, thanks again!
