### ISSUE TITLE
Incorrect File Permissions

### ISSUE THREAD

**Issue by ghost** [OSC/ood-ansible#68]
Owner and Mode are not set in the majority of tasks that are creating files and directories.  On a hardened system, where the umask for the root account is set to be more restrictive, this will cause the configuration to fail. 

A good example is in https://github.com/OSC/ood-ansible/blob/69d895a4421f6159141db09f0dd0a0162ba06fc4/tasks/apps.yml#L1 where app configuration directories are created.  Since the mode is not set in any of the tasks, users logging into OOD won't have read permissions and therefore won't apply any of the configuration (shell/files/bc_desktop/etc..).

**Comment by nlvw** [comment]
I think #88 either fixes this or partially addresses this.

**Comment by johrstrom** [comment]
I think you're right. Thanks for the PR and the update on this ticket!
