### ISSUE TITLE
Host Regex Incorrect Quoting

### ISSUE THREAD

**Issue by nvonwolf** [OSC/ood-ansible#69]
https://github.com/OSC/ood-ansible/blob/69d895a4421f6159141db09f0dd0a0162ba06fc4/templates/ood_portal.yml.j2#L207

When setting a value of `host_regex: 'forge-(l|c)\d+'` (forge-l1,forge-l2,forge-c1,forge-c22, and so on) OOD portal generation will fail.  This is due to the template using double quotes instead of single quotes.   YAML is trying to interpret the escape character '\\' due to the double quotes.

If double quotes are used when setting the variable the Ansible run will fail.  When using single quotes Ansible runs correctly but the portal generation will fill fail due to the issue mentioned before in the template.   Manually fixing the resulting portal yaml file to use single quotes allows the portal generation to run correctly.

**Comment by johrstrom** [comment]
Hey thanks for the ticket! Maybe a `| quote` filter would work.  I'll look into what combinations of quotes and filters work to put what you'd expect there.

**Comment by nvonwolf** [comment]
Using single quotes when setting the regex variable and adjusting the templates to use single quotes fixes the issue.  Wasn't sure if I should put in a pull request so I opened this.

**Comment by johrstrom** [comment]
PRs are welcome of course. I'm going to fix this one in the PR listed above, but feel free to make PRs if you wish. A bug ticket will work just fine too!  Thanks again for opening it.
