### ISSUE TITLE
Passenger not using pre-build passenger_native_support.so

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-ansible#7]
We're building `passenger_native_support.so` in the role itself, however, passenger does not see this when it boots up and builds it all over again. So every user would eventually build the same so library and have their own copy which is both inefficient and a poor installation procedure.

These logs can be seen on boot.
```bash
[ N 2019-10-31 14:48:19.8575 107/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2019-10-31 14:48:19.9076 107/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 107
App 131 output:  [passenger_native_support.so] trying to compile for the current user (jeff) and Ruby interpreter...
App 131 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 131 output:      Compilation successful. The logs are here:
App 131 output:      /tmp/passenger_native_support-36f1sj.log
App 131 output:  [passenger_native_support.so] successfully loaded.
[ N 2019-10-31 14:48:22.5587 107/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
```

**Comment by treydock** [comment]
This must be specific to how you're doing this with this project because my vagrant environments with ondemand-1.7 RPMs are not having this issue.  Are you using the ondemand-runtime SCL environment?  We do this to ensure Passenger from `ondemand-passenger` RPM is setup correctly:

```
export PATH="/opt/ood/ondemand/root/usr/bin:/opt/ood/ondemand/root/usr/sbin${PATH:+:${PATH}}"
export LD_LIBRARY_PATH="/opt/ood/ondemand/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export MANPATH="/opt/ood/ondemand/root/usr/share/man:${MANPATH:-}"
export PKG_CONFIG_PATH="/opt/ood/ondemand/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"
export RUBYLIB="/opt/ood/ondemand/root/usr/share/ruby/vendor_ruby:/opt/ood/ondemand/root/usr/lib64/ruby/vendor_ruby${RUBYLIB:+:${RUBYLIB}}"
```

I see this in Vagrant:

```
[root@ood ~]# locate support.so
/opt/ood/ondemand/root/usr/lib64/ruby/vendor_ruby/passenger_native_support.so
```

This is getting loaded via `RUBYLIB`.

**Comment by johrstrom** [comment]
That's likely it, I was putting it in `/usr/lib64/ruby` but probably need to put it in `/usr/lib64/ruby/2.5.0` where the other `.so` files seem to be.  And on debian it's `/usr/lib/x86_64-linux-gnu/ruby/2.5.0`.

**Comment by johrstrom** [comment]
It could have just been a debian problem. The rhel type parameter didn't need to be changed, though I specified the destination filename just to be sure (I think it could have been copying the `.so` and renaming it to be the directory?).
