### ISSUE TITLE
Update to ood how user mapping is handled

### ISSUE THREAD

**Issue by rps1o2** [OSC/ood-ansible#84]
Because of https://github.com/OSC/ondemand/pull/729, ood-ansible produces a broken installation that tries to use ood_auth_map.regex, which has been removed.

**Comment by johrstrom** [comment]
Hi, can't believe I didn't comment on this ticket too. Thanks for the ticket!

I'm working on fixing up the automation now for our 2.0 release.  As mentioned in #85 we started tagging this role along side OnDemand releases, so 1.8.1 of this role is compatible with 1.8.x of OnDemand.

**Comment by johrstrom** [comment]
This was fixed in #102.
