### ISSUE TITLE
Provide ood-ansible releases in sync to ood releases

### ISSUE THREAD

**Issue by rps1o2** [OSC/ood-ansible#85]
Provide releases that have the target ood version set to the latest ood release that has been tested with that release.

With ood master moving forward, ood-ansible otherwise breaks, like it has in https://github.com/OSC/ood-ansible/issues/84.

**Comment by johrstrom** [comment]
Yea 2.0 and things are not stable. Especially with the automation. If you're building from the source you should set the `version: 1.8.19`.  If you're installing RPMs you should just keep the default rpm url.

Maybe the default version to build should just be the most recent stable tag?

**Comment by johrstrom** [comment]
the default `ood_source_version` is now `v1.8.20` which should build OK on Debain distros now.

I'm working on tagging and releasing a 1.8 compliant version of this playbook to galaxy shortly.

**Comment by johrstrom** [comment]
Hi! This is on ansible galaxy now through `osc.open_ondemand`.
