### ISSUE TITLE
Install fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by zyndagj** [OSC/ood-ansible#93]
Hello, I'm trying to deploy OOD on Ubuntu 20.04 and am hitting the following error:

```
TASK [ood-ansible : move passenger_native_support.so to support libraries] *****************
fatal: [virtual-login01]: FAILED! => changed=false 
  msg: Destination directory /usr/lib/x86_64-linux-gnu/ruby/2.5.0 does not exist
```

Ubuntu 20.04 deploys [ruby 2.7](https://packages.ubuntu.com/focal/ruby) so you may need to have version-specific values in [vars/Ubuntu.yml](https://github.com/OSC/ood-ansible/blob/master/vars/Ubuntu.yml).

**Comment by johrstrom** [comment]
We do supply the configuration to change it, I'd guess that it's `18.04`'s location. I'd have to check on 18's end of life to see which we should default to.

https://github.com/OSC/ood-ansible/blob/b872e5825494c5601eb81a1439d62bed4b095ec0/vars/Ubuntu.yml#L22

PRs welcome! I'd guess in either case we should probably add to the README that we default to Debain:X and to get to Debain:Y you'd want to change these N values.

**Comment by johrstrom** [comment]
Does that configuration item solve your issue @zyndagj?

**Comment by johrstrom** [comment]
Or are you saying we should have a toggle there, or specific OS var files like `vars/Ubuntu-20.04.yml`?

**Comment by zyndagj** [comment]
Assuming you don't want to deprecate 18.04, version specific OS var files might be best. I'm still testing some things on my end, but I'll update this issue with my PR.

**Comment by johrstrom** [comment]
Yea looks like that could be the case. 18.04 seems to have a support lifetime until 2023

**Comment by johrstrom** [comment]
Hi I believe I have a fix in the linked PR. I'm just wrangling the tests now.
